# Generated by Django 4.2.7 on 2024-01-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_comment_template_name_project_template_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='project',
            name='template_name',
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(default='#', max_length=100),
        ),
    ]
